---
- name: Linux Desktop VM customisation
  hosts: localhost
  become: true

  tasks:
    - name: change default openssh server port
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#Port'
        line: Port "{{ vm_ssh_port }}"
      notify: restart ssh
    - name: add vsphere deployment name to hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ vsphere_host_ip }} {{ esxi_host_name  }}"
        insertafter: '^127.0.1.1'
    - name: create .vnc folder
      file:
        path: "/home/{{ vm_user_name }}/.vnc"
        state: directory
        mode: '0755'
    - name: copy vnc xstartup file 
      ansible.builtin.copy:
        src: ./files/xstartup
        dest: "/home/{{ vm_user_name }}/.vnc/xstartup"
        owner: "{{ vm_user_name }}"
        group: "{{ vm_user_name }}"
        mode: '0755'
    - name: create vncpassword for user
      shell: |
        printf "{{ vnc_password }}\n{{ vnc_password }}\n\n" | vncpasswd
        mv /root/.vnc/passwd "/home/{{ vm_user_name }}/.vnc/"
        chown -R "{{ vm_user_name }}:{{ vm_user_name }}" /home/"{{ vm_user_name }}"/.vnc
        chmod 0600 /home/"{{ vm_user_name }}"/.vnc/passwd
        chown -R "{{ vm_user_name }}:{{ vm_user_name }}" /home/"{{ vm_user_name }}"/.vnc/passwd
    - name: create service file for vncserver
      template:
        src: ./templates/vncserver.service.j2
        dest: /etc/systemd/system/vncserver@:2.service
        owner: "{{ vm_user_name }}"
        group: "{{ vm_user_name }}"
        mode: '0755'
    - name: enable vncserver service
      service:
        name: vncserver@:2.service
        enabled: true
      notify: restart vncserver
    - name: install terraform
      ansible.builtin.copy:
        src: ./files/terraform
        dest: /usr/bin/terraform
        owner: root
        group: root
        mode: '0755'
    - name: create folder for terraform vsphere provider 
      file:
        path: /home/"{{ vm_user_name }}"/.terraform.d/plugins/local/registry.terraform.io/hashicorp/vsphere/2.2.0/linux_amd64/
        state: directory
        mode: '0755'
    - name: install terraform vsphere provider
      ansible.builtin.copy:
        src: ./files/terraform-provider-vsphere_v2.2.0_x5
        dest: /home/"{{ vm_user_name }}"/.terraform.d/plugins/local/registry.terraform.io/hashicorp/vsphere/2.2.0/linux_amd64/terraform-provider-vsphere_v2.2.0_x5
        owner: "{{ vm_user_name }}"
        group: "{{ vm_user_name }}"
        mode: '0755'
    - name: install vscode
      shell: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
        sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
        rm -f packages.microsoft.gpg

  handlers:
    - name: restart ssh
      service: name=sshd state=restarted
    - name: restart vncserver
      service:
        name: vncserver@:2.service
        state: restarted
